services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: ${GLUETUN_CONTAINER_NAME}
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${MULLVAD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${MULLVAD_ADDRESS}
      - SERVER_COUNTRIES=${MULLVAD_SERVER_COUNTRY}
    ports:
      - "8081:8081"    # metube
      - "8080:8080"    # qbittorrent
      - "9696:9696"    # prowlarr
      - "8989:8989"    # sonarr
      - "8191:8191"    # flaresolverr
      - "6767:6767"    # bazarr
      - "7878:7878"    # radarr
    volumes:
      - /opt/mediastack/config/gluetun:/gluetun
    restart: unless-stopped

  metube:
    image: ghcr.io/alexta69/metube
    container_name: ${METUBE_CONTAINER_NAME}
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /opt/mediastack/downloads/music:/downloads
    depends_on:
      - gluetun
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: ${QBITTORRENT_CONTAINER_NAME}
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - /opt/mediastack/config/qbittorrent:/config
      - /opt/mediastack/downloads:/downloads
    depends_on:
      - gluetun
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: ${PROWLARR_CONTAINER_NAME}
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /opt/mediastack/config/prowlarr:/config
    depends_on:
      - gluetun
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: ${SONARR_CONTAINER_NAME}
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /opt/mediastack/config/sonarr:/config
      - /opt/mediastack/media/tv:/tv
      - /opt/mediastack/downloads:/downloads
    depends_on:
      - gluetun
    restart: unless-stopped

    radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: ${RADARR_CONTAINER_NAME}
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /opt/mediastack/config/radarr:/config
      - /opt/mediastack/media/movies:/movies
      - /opt/mediastack/downloads:/downloads
    depends_on:
      - gluetun
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: ${BAZARR_CONTAINER_NAME}
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /opt/mediastack/config/bazarr:/config
      - /opt/mediastack/media/tv:/tv
    depends_on:
      - gluetun
    restart: unless-stopped

  # lidarr:
  #   image: lscr.io/linuxserver/lidarr:latest
  #   container_name: ${LIDARR_CONTAINER_NAME}
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #   volumes:
  #     - /opt/mediastack/config/lidarr:/config
  #     - /opt/mediastack/media/music:/music
  #     - /opt/mediastack/downloads/music:/downloads/music
  #   ports:
  #     - "8686:8686"
  #   restart: unless-stopped

  flaresolverr:
    image: flaresolverr/flaresolverr
    container_name: ${FLARESOLVERR_CONTAINER_NAME}
    network_mode: "service:gluetun"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    depends_on:
      - gluetun
    restart: unless-stopped 

  filebrowser:
    image: filebrowser/filebrowser
    container_name: ${FILEBROWSER_CONTAINER_NAME}
    volumes:
      - /opt/mediastack:/srv
      - /opt/mediastack/config/filebrowser/database:/database
      - /opt/mediastack/config/filebrowser/config:/config
    ports:
      - "8082:80"
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: ${JELLYFIN_CONTAINER_NAME}
    environment:
      - TZ=${TZ}
    volumes:
      - /opt/mediastack/config/jellyfin:/config
      - /opt/mediastack/media:/media:ro
    ports:
      - "8096:8096"
    restart: unless-stopped